apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Manikandannew/Helm-projects.git
    targetRevision: master
    path: helm-charts    # this points to your Chart.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}

